### ISSUE TITLE
"Invalid octal format" error extracting node-headers.tar

### ISSUE THREAD

**Issue by zcbenz** [nonzzz/tar#4]
First download the file:

```
curl https://nodejs.org/dist/latest/node-v22.7.0-headers.tar.gz | gunzip > test.tar
```

Then extract with code:

```
  const readable = fs.createReadStream('test.tar');
  const extract = tar.createExtract();
  readable.pipe(extract.receiver);
```

Error is thrown:

```
/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:102
            throw new Error(ERROR_MESSAGES.INVALID_OCTAL_FORMAT);
                  ^

Error: Invalid octal format
    at decodeOctal (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:102:19)
    at decode (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:229:18)
    at decodeHead (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:568:29)
    at Extract.transport (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:635:18)
    at Writable.write [as _write] (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:669:22)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at ReadStream.ondata (node:internal/streams/readable:1007:22)
    at ReadStream.emit (node:events:520:28)
```

**Comment by nonzzz** [comment]
'@LongLink' isn't support in past. I release a new version fix this problem.

**Comment by zcbenz** [comment]
Awesome work, thanks a lot!
